INSERT INTO "PILOT"."SP_MODULES" (ID, DESCRIPTION) VALUES ('1', 'Pilot');

INSERT INTO "PILOT"."UM_USERS" (ID, NAME, USERNAME, TEMP_KEY, SYSTEM_FLAG, INSERTION_DATE, LAST_UPDATE_DATE) VALUES (UM_SEQ.nextVal, 'Ahmed', 'ahmed', 'ahmed', '0', sysdate, null);

INSERT INTO "PILOT"."UM_AUDIT_LOGS" (ID, MODULE_ID, USER_ID, OPERATION, OPERATION_DATE, CONTENT_ENTITY, CONTENT_ID, CONTENT) VALUES (UM_AUDIT_SEQ.nextVal, '1', '1', 'INSERT', sysdate, 'Config', '1', 'config: value');

INSERT INTO "PILOT"."SP_CONFIG" (ID, CODE, CONFIG_VALUE, DESCRIPTION, INSERTION_DATE, LAST_UPDATE_DATE) VALUES (SP_SEQ.nextVal, 'REPORTS_ROOT', 'C:\Reports', 'Reports root', sysdate, null);
INSERT INTO "PILOT"."SP_CONFIG" (ID, CODE, CONFIG_VALUE, DESCRIPTION, INSERTION_DATE, LAST_UPDATE_DATE) VALUES (SP_SEQ.nextVal, 'SCHEMA_NAME', 'PILOT', 'Schema name', sysdate, null);
INSERT INTO "PILOT"."SP_CONFIG" (ID, CODE, CONFIG_VALUE, DESCRIPTION, INSERTION_DATE, LAST_UPDATE_DATE) VALUES (SP_SEQ.nextVal, 'PILOT', '1', 'Pilot Module Id', sysdate, null);
INSERT INTO "PILOT"."SP_CONFIG" (ID, CODE, CONFIG_VALUE, DESCRIPTION, INSERTION_DATE, LAST_UPDATE_DATE) VALUES (SP_SEQ.nextVal, 'Test 22', 'تجربة', 'Test', sysdate, null);

COMMIT;
