DROP TABLE SP_CONFIG;
DROP TABLE UM_AUDIT_LOGS;
DROP TABLE UM_PRIVILEGES;
DROP TABLE UM_GROUP_DETAILS;
DROP TABLE UM_USERS;
DROP TABLE UM_URL_ACTIONS;
DROP TABLE UM_URLS;
DROP TABLE UM_GROUPS;
DROP TABLE SP_MODULES;

DROP SEQUENCE SP_SEQ;
DROP SEQUENCE UM_SEQ;
DROP SEQUENCE UM_AUDIT_SEQ;

---------------------------------------------------------------------------------------------
CREATE TABLE SP_MODULES 
(
  ID NUMBER NOT NULL 
, DESCRIPTION VARCHAR2(200 CHAR) NOT NULL 
, CONSTRAINT SP_MODULES_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_SP_MODULES ON SP_MODULES (ID ASC) 
  )
  ENABLE 
);

ALTER TABLE SP_MODULES
ADD CONSTRAINT U_SP_MODULES_DESC UNIQUE 
(
  DESCRIPTION 
)
ENABLE;

CREATE TABLE SP_CONFIG 
(
  ID NUMBER NOT NULL 
, CODE VARCHAR2(50 CHAR) NOT NULL 
, CONFIG_VALUE VARCHAR2(200 CHAR) NOT NULL 
, DESCRIPTION VARCHAR2(200 CHAR) NOT NULL 
, INSERTION_DATE DATE NOT NULL 
, LAST_UPDATE_DATE DATE 
, CONSTRAINT PK_SP_CONFIG PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE UM_USERS 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(200 CHAR) NOT NULL 
, USERNAME VARCHAR2(50 CHAR) NOT NULL 
, SYSTEM_FLAG NUMBER(1) NOT NULL
, TEMP_KEY VARCHAR2(50 CHAR) NOT NULL
, INSERTION_DATE DATE NOT NULL 
, LAST_UPDATE_DATE DATE
, CONSTRAINT PK_UM_USERS PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE UM_USERS
ADD CONSTRAINT U_UM_USERS_USERNAME UNIQUE 
(
  USERNAME 
)
ENABLE;

CREATE TABLE UM_URLS 
(
  ID NUMBER NOT NULL 
, CODE VARCHAR2(100 CHAR) 
, URL VARCHAR2(200 CHAR) 
, MODULE_ID NUMBER NOT NULL 
, NAME_KEY VARCHAR2(200 CHAR) NOT NULL 
, PARENT_ID NUMBER 
, ORDER_BY NUMBER NOT NULL 
, CLASSIFICATION NUMBER(1) NOT NULL 
, ACTIVE_FLAG NUMBER(1) NOT NULL 
, CONSTRAINT PK_UM_URLS PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE UM_URLS
ADD CONSTRAINT U_UM_URLS_MODULE_ID_CODE UNIQUE 
(
  MODULE_ID 
, CODE 
)
USING INDEX 
(
    CREATE UNIQUE INDEX UM_URLS ON UM_URLS (MODULE_ID ASC, CODE ASC) 
)
 ENABLE;

ALTER TABLE UM_URLS
ADD CONSTRAINT U_UM_URLS_MODULE_ID_URL UNIQUE 
(
  MODULE_ID 
, URL 
)
ENABLE;

ALTER TABLE UM_URLS
ADD CONSTRAINT FK_UM_URLS_PARENT_ID FOREIGN KEY
(
  PARENT_ID 
)
REFERENCES UM_URLS
(
  ID 
)
ENABLE;

ALTER TABLE UM_URLS
ADD CONSTRAINT FK_UM_URLS_SP_MODULES_MODULE_ID FOREIGN KEY
(
  MODULE_ID 
)
REFERENCES SP_MODULES
(
  ID 
)
ENABLE;

COMMENT ON COLUMN UM_URLS.CLASSIFICATION IS '0: Non Menu Screen, 1: Menu Screen, 2: Service URL ';

CREATE TABLE UM_URL_ACTIONS 
(
  ID NUMBER NOT NULL 
, ACTION VARCHAR2(100 CHAR) NOT NULL
, URL_ID NUMBER NOT NULL
, DESCRIPTION VARCHAR2(200 CHAR) NOT NULL 
, CONSTRAINT PK_UM_URL_ACTIONS PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE UM_URL_ACTIONS
ADD CONSTRAINT U_UM_URL_ACTIONS_URL_ID_ACTION UNIQUE 
(
  URL_ID 
, ACTION 
)
 ENABLE;

ALTER TABLE UM_URL_ACTIONS
ADD CONSTRAINT FK_UM_URL_ACTIONS_UM_URLS_URL_ID FOREIGN KEY
(
  URL_ID 
)
REFERENCES UM_URLS
(
  ID 
)
ENABLE;

CREATE TABLE UM_GROUPS
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(200 CHAR) NOT NULL
, MODULE_ID NUMBER NOT NULL
, CLASSIFICATION NUMBER(1) NOT NULL
, INSERTION_DATE DATE NOT NULL 
, LAST_UPDATE_DATE DATE
, CONSTRAINT PK_UM_GROUPS PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE UM_GROUPS
ADD CONSTRAINT FK_UM_GROUPS_SP_MODULES_MODULE_ID FOREIGN KEY
(
  MODULE_ID 
)
REFERENCES SP_MODULES
(
  ID 
)
ENABLE;

COMMENT ON COLUMN UM_GROUPS.CLASSIFICATION IS '1: Users Group, 2: URLs Group, 3: URL Actions Group ';

CREATE TABLE UM_GROUP_DETAILS
(
  ID NUMBER NOT NULL 
, GROUP_ID NUMBER NOT NULL
, USER_ID NUMBER
, URL_ID NUMBER
, URL_ACTION_ID NUMBER
, DATA_DIMENSION NUMBER
, INSERTION_DATE DATE NOT NULL 
, LAST_UPDATE_DATE DATE
, CONSTRAINT PK_UM_GROUP_DETAILS PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE UM_GROUP_DETAILS
ADD CONSTRAINT U_UM_GROUP_DETAILS_GROUP_ID_USER_ID UNIQUE 
(
  GROUP_ID 
, USER_ID 
)
ENABLE;

ALTER TABLE UM_GROUP_DETAILS
ADD CONSTRAINT U_UM_GROUP_DETAILS_GROUP_ID_URL_ID UNIQUE 
(
  GROUP_ID 
, URL_ID 
)
ENABLE;

ALTER TABLE UM_GROUP_DETAILS
ADD CONSTRAINT U_UM_GROUP_DETAILS_GROUP_ID_URL_ACTION_ID UNIQUE 
(
  GROUP_ID 
, URL_ACTION_ID 
)
ENABLE;

ALTER TABLE UM_GROUP_DETAILS
ADD CONSTRAINT U_UM_GROUP_DETAILS_GROUP_ID_DATA_DIMENSION UNIQUE 
(
  GROUP_ID 
, DATA_DIMENSION 
)
ENABLE;

ALTER TABLE UM_GROUP_DETAILS
ADD CONSTRAINT FK_UM_GROUP_DETAILS_UM_GROUPS_GROUP_ID FOREIGN KEY
(
  GROUP_ID 
)
REFERENCES UM_GROUPS
(
  ID 
)
ENABLE;

ALTER TABLE UM_GROUP_DETAILS
ADD CONSTRAINT FK_UM_GROUP_DETAILS_UM_USERS_USER_ID FOREIGN KEY
(
  USER_ID 
)
REFERENCES UM_USERS
(
  ID 
)
ENABLE;

ALTER TABLE UM_GROUP_DETAILS
ADD CONSTRAINT FK_UM_GROUP_DETAILS_UM_URLS_URL_ID FOREIGN KEY
(
  URL_ID 
)
REFERENCES UM_URLS
(
  ID 
)
ENABLE;

ALTER TABLE UM_GROUP_DETAILS
ADD CONSTRAINT FK_UM_GROUP_DETAILS_UM_URL_ACTIONS_URL_ACTION_ID FOREIGN KEY
(
  URL_ACTION_ID 
)
REFERENCES UM_URL_ACTIONS
(
  ID 
)
ENABLE;


CREATE TABLE UM_PRIVILEGES
(
  ID NUMBER NOT NULL 
, USER_GROUP_ID NUMBER NOT NULL
, PRIVILEGE_GROUP_ID NUMBER NOT NULL
, INSERTION_DATE DATE NOT NULL 
, LAST_UPDATE_DATE DATE
, CONSTRAINT PK_UM_PRIVILEGES PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE UM_PRIVILEGES
ADD CONSTRAINT U_UM_PRIVILEGES_USER_GROUP_ID_PRIVILEGE_GROUP_ID UNIQUE 
(
  USER_GROUP_ID 
, PRIVILEGE_GROUP_ID 
)
ENABLE;

ALTER TABLE UM_PRIVILEGES
ADD CONSTRAINT FK_UM_PRIVILEGES_UM_GROUPS_USER_GROUP_ID FOREIGN KEY
(
  USER_GROUP_ID 
)
REFERENCES UM_GROUPS
(
  ID 
)
ENABLE;

ALTER TABLE UM_PRIVILEGES
ADD CONSTRAINT FK_UM_PRIVILEGES_UM_GROUPS_PRIVILEGE_GROUP_ID FOREIGN KEY
(
  PRIVILEGE_GROUP_ID 
)
REFERENCES UM_GROUPS
(
  ID 
)
ENABLE;

CREATE TABLE UM_AUDIT_LOGS
(
  ID NUMBER NOT NULL 
, MODULE_ID NUMBER NOT NULL
, USER_ID NUMBER NOT NULL
, OPERATION VARCHAR2(10 CHAR) NOT NULL
, OPERATION_DATE DATE NOT NULL
, CONTENT_ENTITY VARCHAR2(200 CHAR) NOT NULL
, CONTENT_ID VARCHAR2(100 CHAR) NOT NULL
, CONTENT VARCHAR2(2000 CHAR) NOT NULL
, CONSTRAINT PK_UM_AUDIT_LOGS PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


ALTER TABLE UM_AUDIT_LOGS
ADD CONSTRAINT FK_UM_AUDIT_LOGS_SP_MODULES_MODULE_ID FOREIGN KEY
(
  MODULE_ID 
)
REFERENCES SP_MODULES
(
  ID 
)
ENABLE;

ALTER TABLE UM_AUDIT_LOGS
ADD CONSTRAINT FK_UM_AUDIT_LOGS_UM_USERS_USER_ID FOREIGN KEY
(
  USER_ID 
)
REFERENCES UM_USERS
(
  ID 
)
ENABLE;

---------------------------------------------------------------------------------------------

CREATE SEQUENCE SP_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE UM_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE UM_AUDIT_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
