package com.code.dal.entities;

public class QueryConfiguration {
    public static final String SP_CONFIGURATION_GET_CONFIGURATIONS = "SP_CONFIGURATION_GET_CONFIGURATIONS",
	    SP_CONFIGURATION_GET_CONFIGURATIONS_PARAMS = "P_CODE,P_ESC_SEARCH_STR",
	    UM_AUDIT_LOG_GET_AUDIT_LOGS = "UM_AUDIT_LOG_GET_AUDIT_LOGS",
	    UM_AUDIT_LOG_GET_AUDIT_LOGS_PARAMS = "P_CONTENT_ENTITY,P_CONTENT_ID,P_OPERATION,P_USER_ID,P_FROM_DATE_FLAG,P_FROM_DATE,P_TO_DATE_FLAG,P_TO_DATE,P_CONTENT,P_ESC_SEARCH_STR,P_ESC_SEARCH_LONG,P_ESC_SEARCH_INT";

}
