package com.code.dal.entities;

public class QueryConfiguration {
    public static final String SP_CONFIGURATION_GET_CONFIGURATIONS = "SP_CONFIGURATION_GET_CONFIGURATIONS",
	    SP_CONFIGURATION_GET_CONFIGURATIONS_PARAMS = "P_CODE,P_ESC_SEARCH_STR",

	    UM_AUDIT_LOG_GET_AUDIT_LOGS = "UM_AUDIT_LOG_GET_AUDIT_LOGS",
	    UM_AUDIT_LOG_GET_AUDIT_LOGS_PARAMS = "P_CONTENT_ENTITY,P_CONTENT_ID,P_OPERATION,P_USER_ID,P_FROM_DATE_FLAG,P_FROM_DATE,P_TO_DATE_FLAG,P_TO_DATE,P_CONTENT,P_ESC_SEARCH_STR,P_ESC_SEARCH_LONG,P_ESC_SEARCH_INT",
	    UM_GROUP_GET_GROUPS = "UM_GROUP_GET_GROUPS",
	    UM_GROUP_GET_GROUPS_PARAMS = "P_MODULE_ID,P_CLASSIFICATION,P_NAME,P_USER_ID,P_URL_ID,P_URL_ACTION_ID,P_ESC_SEARCH_STR,P_ESC_SEARCH_LONG",
	    UM_URL_GET_USER_URLS = "UM_URL_GET_USER_URLS",
	    UM_URL_GET_USER_URLS_PARAMS = "P_USER_ID,P_MODULE_ID",
	    UM_URL_GET_GROUP_URLS = "UM_URL_GET_GROUP_URLS",
	    UM_URL_GET_GROUP_URLS_PARAMS = "P_GROUP_ID",
	    UM_URL_ACTION_GET_GROUP_URL_ACTIONS = "UM_URL_ACTION_GET_GROUP_URL_ACTIONS",
	    UM_URL_ACTION_GET_GROUP_URL_ACTIONS_PARAMS = "P_GROUP_ID",
	    UM_USER_GET_USERS_BY_URL = "UM_USER_GET_USERS_BY_URL",
	    UM_USER_GET_USERS_BY_URL_PARAMS = "P_URL_ID",
	    UM_USER_GET_USERS_BY_ACTION = "UM_USER_GET_USERS_BY_ACTION",
	    UM_USER_GET_USERS_BY_ACTION_PARAMS = "P_URL_ACTION_ID",
	    UM_USER_URL_ACTION_DATA_GET_USER_URL_ACTIONS = "UM_USER_URL_ACTION_DATA_GET_USER_URL_ACTIONS",
	    UM_USER_URL_ACTION_DATA_GET_USER_URL_ACTIONS_PARAMS = "P_USER_ID,P_MODULE_ID";

}
