package com.code.enums;

public enum ErrorMessageCodesEnum {

    // ------------------------------------ CORE ERRORS ----------------------------------------
    INVALID_DATE,
    NO_DATA_FOUND,
    FILE_NOT_FOUND,
    GENERAL,

    SHEET_UNSUPPORTED_FILE_FORMAT,
    SHEET_INDEX_OUT_OF_BOUND,
    SHEET_ROW_OUT_OF_BOUND,
    SHEET_COLUMN_OUT_OF_BOUND,
    SHEET_UNSUPPORTED_CELL_TYPE,

    WF_REQUESTER_OR_BENEFICIARY_MANDATORY,
    WF_REQUESTER_OR_BENEFICIARY_OR_ASSIGNEE_MANDATORY,

    WF_DELEGATOR_OR_DELEGATE_MANDATORY,
    WF_DELEGATION_LOOP,
    WF_DELEGATOR_CANNOT_BE_THE_SAME_AS_DELEGATE,
    WF_DELEGATOR_ALREADY_HAS_TOTAL_DELEGATION,
    WF_DELEGATE_ALREADY_HAS_PARTIAL_DELEGATION,
    WF_DELEGATE_ALREADY_HAS_TOTAL_DELEGATION,
    WF_DELEGATOR_ALREADY_HAS_PARTIAL_DELEGATION,

    WF_TASKS_MANDATORY,
    WF_TASK_REFUSE_REASONS_MANDATORY,
    WF_TASK_REFUSE_REASONS_SHOULD_BE_EMPTY,
    WF_TASK_NOTES_MANDATORY,

    // ------------------------------------ DOMAIN ERRORS --------------------------------------
    WF_MISSION_DESTINATION_MANDATORY,

    MSN_MAIN_FIELDS_MNDATORY,
    MSN_DETAIL_FIELDS_MNDATORY,
    MSN_ONE_EMPLOYEE_MANDATORY,
    MSN_EMPLOYEE_REPETITION,
    MSN_DATES_CONFLICT,
    MSN_DATES_BEFORE_HIRING,
    MSN_NO_BALANCE,
    MSN_ACTUAL_FIELDS_MNDATORY,
    MSN_ACTUAL_SHOULD_BE_IN_SAME_YEAR,
    MSN_START_END_SHOULD_BE_IN_SAME_YEAR,
    MSN_ACTUAL_SHOULD_NOT_CHANGE_IN_ABSENCE,
    MSN_ABSENCE_REASONS_NOT_ALLOWED,
    MSN_JOINING_DATE_MANDATORY,
    MSN_JOINING_DATE_NOT_ALLOWED,
    MSN_JOINING_DATE_INVALID;

}
